import { Footer } from "./Footer";
import { NavBar } from "./NavBar";
import Head from "next/head";

export function Layout({ children }) {
  return (
    <>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="main-container">{children}</main>
      <Footer />
    </>
  );
}
